<?php
return array (
  'NAME1' => 'WELCOME TO 2DMater',
  'NAME2' => 'High quality two-dimensional single crystal manufacturers add icing on the cake to a better life',
  'NAME3' => '',
  'NAME4' => 'HOT PRODUCT',
  'NAME5' => 'PRODUCT CATEGORYⅠ',
  'NAME6' => 'PRODUCT CATEGORYⅡ',
  'NAME7' => '',
  'NAME8' => '高质量的二维单晶体制造商',
  'NAME9' => '',
  'NAME10' => '热门产品',
  'NAME11' => '产品类别Ⅰ',
  'NAME12' => '产品类别Ⅱ',
  'NAME13' => '',
  'NAME14' => '',
  'NAME15' => '',
  'NAME16' => '',
  'NAME17' => '',
  'NAME18' => '',
  'NAME19' => '',
  'NAME20' => '',
  'NAME21' => '',
  'NAME22' => '',
  'NAME23' => '',
  'NAME24' => '',
  'NAME25' => '',
  'NAME26' => '',
  'NAME27' => '',
  'NAME28' => '',
  'NAME29' => '',
  'NAME30' => '',
  'NAME31' => '',
  'NAME32' => '',
  'NAME33' => '',
  'NAME34' => '',
  'NAME35' => '',
  'NAME36' => '',
  'NAME37' => '',
  'NAME38' => '',
  'NAME39' => '',
  'NAME40' => '',
);
?>